// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/castai/slog-buffer/pkg/store (interfaces: Store,Flusher,ErrorHandler)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mocks.go -package=mocks github.com/castai/slog-buffer/pkg/store Store,Flusher,ErrorHandler
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockStore is a mock of Store interface.
type MockStore[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder[T]
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder[T any] struct {
	mock *MockStore[T]
}

// NewMockStore creates a new mock instance.
func NewMockStore[T any](ctrl *gomock.Controller) *MockStore[T] {
	mock := &MockStore[T]{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore[T]) EXPECT() *MockStoreMockRecorder[T] {
	return m.recorder
}

// Run mocks base method.
func (m *MockStore[T]) Run(ctx context.Context) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Run", ctx)
}

// Run indicates an expected call of Run.
func (mr *MockStoreMockRecorder[T]) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockStore[T])(nil).Run), ctx)
}

// Write mocks base method.
func (m *MockStore[T]) Write(entries ...T) {
	m.ctrl.T.Helper()
	varargs := []any{}
	for _, a := range entries {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "Write", varargs...)
}

// Write indicates an expected call of Write.
func (mr *MockStoreMockRecorder[T]) Write(entries ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Write", reflect.TypeOf((*MockStore[T])(nil).Write), entries...)
}

// MockFlusher is a mock of Flusher interface.
type MockFlusher[T any] struct {
	ctrl     *gomock.Controller
	recorder *MockFlusherMockRecorder[T]
	isgomock struct{}
}

// MockFlusherMockRecorder is the mock recorder for MockFlusher.
type MockFlusherMockRecorder[T any] struct {
	mock *MockFlusher[T]
}

// NewMockFlusher creates a new mock instance.
func NewMockFlusher[T any](ctrl *gomock.Controller) *MockFlusher[T] {
	mock := &MockFlusher[T]{ctrl: ctrl}
	mock.recorder = &MockFlusherMockRecorder[T]{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFlusher[T]) EXPECT() *MockFlusherMockRecorder[T] {
	return m.recorder
}

// Flush mocks base method.
func (m *MockFlusher[T]) Flush(ctx context.Context, entries []T) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Flush", ctx, entries)
	ret0, _ := ret[0].(error)
	return ret0
}

// Flush indicates an expected call of Flush.
func (mr *MockFlusherMockRecorder[T]) Flush(ctx, entries any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Flush", reflect.TypeOf((*MockFlusher[T])(nil).Flush), ctx, entries)
}

// MockErrorHandler is a mock of ErrorHandler interface.
type MockErrorHandler struct {
	ctrl     *gomock.Controller
	recorder *MockErrorHandlerMockRecorder
	isgomock struct{}
}

// MockErrorHandlerMockRecorder is the mock recorder for MockErrorHandler.
type MockErrorHandlerMockRecorder struct {
	mock *MockErrorHandler
}

// NewMockErrorHandler creates a new mock instance.
func NewMockErrorHandler(ctrl *gomock.Controller) *MockErrorHandler {
	mock := &MockErrorHandler{ctrl: ctrl}
	mock.recorder = &MockErrorHandlerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockErrorHandler) EXPECT() *MockErrorHandlerMockRecorder {
	return m.recorder
}

// OnError mocks base method.
func (m *MockErrorHandler) OnError(err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "OnError", err)
}

// OnError indicates an expected call of OnError.
func (mr *MockErrorHandlerMockRecorder) OnError(err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OnError", reflect.TypeOf((*MockErrorHandler)(nil).OnError), err)
}
