name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Secret Scanning
        uses: trufflesecurity/trufflehog@main
        with:
          extra_args: --only-verified

      - name: Setup Go
        uses: actions/setup-go@41dfa10bad2bb2ae585af6ee5bb4d7d973ad74ed # v5
        with:
          go-version-file: "go.mod"

      - name: Run golangci-lint
        if: ${{ github.event_name == 'pull_request' && !contains(env.head_commit_message, '#skip-lint') }}
        uses: golangci/golangci-lint-action@v6.0.1
        with:
          args: -v --timeout=5m
          version: v1.64.2

      - name: Test
        if: ${{ github.event_name == 'pull_request' && !contains(env.head_commit_message, '#skip-test') }}
        run: make test
